### PR TITLE
Analysis

### PR DESCRIPTION
**Pull request by bereketli**
the default zoom is made to "fit to width",result scrolls when the dictionary has multiple key value pairs, the result moves up ward

### CODE REVIEW

**Comment by bereketli** [comment]
ask and accept AI analysis , add loading spiner and error management in sign up

**Comment by bereketli** [comment]
number of column is increased to 4, width of AI recommendation is made screen

**Comment by bereketli** [comment]
align in center, bigger button , rename analyse resume to AI analysis, make the two buttons visible simultaneously

**Review by smttsp — APPROVED** [review]
lgtm

**Pull request merged**
